/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Daftar;

import javax.swing.JButton;
import javax.swing.JFrame;

import java.util.Date;  
import java.text.DateFormat;  
import java.text.SimpleDateFormat;  
   

   
   
       
   
public class Orthopedi extends javax.swing.JFrame {
    String KartuPasienPanel;
 
    /** 
     * Creates new form Poli
     */
    public Orthopedi() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        umumO = new javax.swing.JRadioButton();
        tulangbelakangO = new javax.swing.JRadioButton();
        cideraO = new javax.swing.JRadioButton();
        rekonstruksiO = new javax.swing.JRadioButton();
        cetakO = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 200));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 60));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("News706 BT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT DATANG DI POLI ORTHOPEDI");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Klinik:");

        umumO.setText("Umum");
        umumO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umumOActionPerformed(evt);
            }
        });

        tulangbelakangO.setText("Tulang Belakang");
        tulangbelakangO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tulangbelakangOActionPerformed(evt);
            }
        });

        cideraO.setText("Cidera");
        cideraO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cideraOActionPerformed(evt);
            }
        });

        rekonstruksiO.setText("Rekonstruksi");
        rekonstruksiO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekonstruksiOActionPerformed(evt);
            }
        });

        cetakO.setBackground(new java.awt.Color(51, 51, 255));
        cetakO.setForeground(new java.awt.Color(255, 255, 255));
        cetakO.setText("CETAK ");
        cetakO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rekonstruksiO)
                    .addComponent(cideraO)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tulangbelakangO)
                        .addGap(27, 27, 27)
                        .addComponent(cetakO))
                    .addComponent(umumO))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(umumO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tulangbelakangO)
                    .addComponent(cetakO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cideraO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rekonstruksiO)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void Kode(){
        
    }
    private String nama,nomor,umur, alamat, poli,klinik,telepon,jenisKelamin,tanggal,waktu;
    public void setNama(String nama){
        this.nama=nama;
    }
    public String getNama(){
        return this.nama;
    }

    public String getNomor() {
        return nomor;
    }

    public void setNomor(String nomor) {
        this.nomor = nomor;
    }

    public String getUmur() {
        return umur;
    }

    public void setUmur(String umur) {
        this.umur = umur;
    }

    public String getAlamat() {
        return alamat;
    }

    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    public String getTelepon() {
        return telepon;
    }

    public void setTelepon(String telepon) {
        this.telepon = telepon;
    }

    public String getJenisKelamin() {
        return jenisKelamin;
    }

    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    
    public String getPoli(){
        return poli;
    }
    public void setPoli(String poli){
        this.poli=poli;
    }
    public String getKlinik(){
        return klinik;
    }
    public void setKlinik(String klinik){
        this.klinik=klinik;
    }

    public void setTanggal(String tanggal) {
        this.tanggal = tanggal;
    }

    public void setWaktu(String waktu) {
        this.waktu = waktu;
    }
    
    
     public String getTanggal() {  
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
        Date date = new Date();  
        return dateFormat.format(date);  
    }  
     
    public String getWaktu() {  
        DateFormat dateFormat = new SimpleDateFormat("HH:mm");  
        Date date = new Date();  
        return dateFormat.format(date);  
    } 
//    public void setKode(){
//        
//    }
 
    private void cetakOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakOActionPerformed
        // TODO add your handling code here:
        KartuPasien KP=new KartuPasien();
        KP.setNamaPasien(getNama());
        KP.setAlamatPasien(getAlamat());
        KP.setJenisKelaminPasien(getJenisKelamin());
        KP.setPoliPasien(getPoli());
        KP.setKlinikPasien(getKlinik());
        if(umumO.isSelected()){
            KP.setKlinikPasien(umumO.getText());
        }
        else if(tulangbelakangO.isSelected()){
            KP.setKlinikPasien(tulangbelakangO.getText());
        }
        else if(cideraO.isSelected()){
            KP.setKlinikPasien(cideraO.getText());
        }
        else {
            KP.setKlinikPasien(rekonstruksiO.getText());
        }
        KP.setTanggalPasien(getTanggal());
        KP.setWaktuPasien(getWaktu());
        
        KP.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cetakOActionPerformed

    private void umumOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umumOActionPerformed
        // TODO add your handling code here:
        if(umumO.isSelected()){
            tulangbelakangO.setSelected(false);
            cideraO.setSelected(false);
            rekonstruksiO.setSelected(false);
        }
    }//GEN-LAST:event_umumOActionPerformed

    private void tulangbelakangOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tulangbelakangOActionPerformed
        // TODO add your handling code here:
        if(tulangbelakangO.isSelected()){
            umumO.setSelected(false);
            cideraO.setSelected(false);
            rekonstruksiO.setSelected(false);
        }
    }//GEN-LAST:event_tulangbelakangOActionPerformed

    private void cideraOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cideraOActionPerformed
        // TODO add your handling code here:
        if(cideraO.isSelected()){
            tulangbelakangO.setSelected(false);
            umumO.setSelected(false);
            rekonstruksiO.setSelected(false);
        }
    }//GEN-LAST:event_cideraOActionPerformed

    private void rekonstruksiOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekonstruksiOActionPerformed
        // TODO add your handling code here:
        if(rekonstruksiO.isSelected()){
            tulangbelakangO.setSelected(false);
            cideraO.setSelected(false);
            umumO.setSelected(false);
        }
    }//GEN-LAST:event_rekonstruksiOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orthopedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orthopedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orthopedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orthopedi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orthopedi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cetakO;
    private javax.swing.JRadioButton cideraO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton rekonstruksiO;
    private javax.swing.JRadioButton tulangbelakangO;
    private javax.swing.JRadioButton umumO;
    // End of variables declaration//GEN-END:variables
}
